LinkHouse/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/urls.py
from website import views
from django.urls import path

urlpatterns = [
    path('', views.home, name="home"),
    path('profile/<slug:profile_slug>', views.profile, name="profile")
]

website/models.py
from django.db import models
from django.template.defaultfilters import slugify
# Create your models here.

class Profile(models.Model):
    name = models.TextField()
    desc = models.TextField()
    logo = models.ImageField(upload_to='profile/logo/', blank=True,null=True)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Profile, self).save(*args, **kwargs)
    
class Link(models.Model):
    class Type_Menu(models.TextChoices):
        FOOD = "1", "Food"
        DRINKS = "2", "Drinks/Bar"

    linktype = models.CharField(choices=Type_Menu.choices, default=Type_Menu.FOOD, max_length=100)
    title = models.CharField(max_length=200)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    url = models.URLField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return f"{self.profile.name} - Link {self.id}"

website/views.py
from django.shortcuts import render, get_object_or_404
from website.models import *

# Create your views here.

def home(request):
    profile_objs = Profile.objects.all()
    context = {
        'profiles': profile_objs,
    }
    return render(request, "home.html", context)

def profile(request, profile_slug):
    profile_obj = get_object_or_404(Profile, slug=profile_slug)

    context = {
        'profile' : profile_obj,
    }

    return render(request, "profile.html", context)

templates/base.html
{% load static %}
<html class="bg-bg-color">
    <head>
        <title>{% block title %}LinkHouse {% endblock title%}</title>

        <link rel="stylesheet" href="{% static 'css/output.css' %}">

        <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    </head>
    {% block header %}

        <div class="flex justify-items-center justify-center bg-bg-color">
            <img src="{% static 'images/logo-lh.svg' %}" class="w-28 h-36" alt="linkhouselogo">
        </div>

    {% endblock header %}

    <main class="h-screen bg-bg-color">
        {% block Content %}
            
            <h1>Somthing went wrong!</h1>
            
        {% endblock Content %}
    </main>
</html>



templates/home.html
{% extends 'base.html' %}
{% load static %}


{% comment %} {% block header %}
    
{% endblock header %} {% endcomment %}

{% block Content %}

    <h1 class="underline font-serif mx-10 text-4xl mb-10">Restaurants</h1>

    {% for pro in profiles %}
    <a href="{% url 'profile' pro.slug %}">
        <div class="flex border-2 border-black rounded-lg pattern-charlie mx-10 justify-center items-center">
            <div class="w-1/3 h-full">
                {% if pro.logo %}
                    <img src="{{pro.logo.url}}" class="w-full rounded-r-lg" alt="{{pro.slug}}-logo">
                {% else %}
                    <img src="{% static 'images/logo-lh.svg' %}" class="w-full rounded-lg" alt="linkhouselogo">
                {% endif %}
            </div>
            

            <div class="w-5/6 relative">
                <p class="text-white font-Barlow text-3xl m-10">
                    {{pro.name}}
                </p>

                <p class="text-white font-Lora text-xl m-10">
                    {{pro.desc}}
                </p>

                
                    <span class="h-10 transition-transform duration-300 hover:translate-x-2 bottom-0 right-0 absolute material-symbols-outlined text-white mr-5 mb-5" style="font-size: 50px;">
                        trending_flat
                    </span>
                
                
            </div>
        </div>
    </a>
        
    {% endfor %}

{% endblock Content %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <div class="flex justify-items-center justify-center ">
        {% if profile.logo %}
            <img src="{{profile.logo.url}}" class="h-36 m-5" alt="{{profile.slug}}-logo">
        {% else %}
            <img src="{% static 'images/logo-lh.svg' %}" class="w-28 h-36" alt="linkhouselogo">
        {% endif %}
        
    </div>
{% endblock header %}

{% block Content %}
<div class="flex justify-items-center justify-center">
    <h2 class="text-5xl font-Barlow mt-10 text-center">{{profile.name}}</h2>
</div>
    {% for link in profile.link_set.all %}
    <a href="{{link.url}}">
        <div class="flex justify-items-center h-36 justify-center rounded-lg m-10 border-2 border-amber-500 bg-opacity-60
        {% if link.linktype == "1" %}
            pattern-food
        {% elif link.linktype == "2" %}
            pattern-diamonds
        {% endif %}
        " 
        
        >
            
            <h3 class="font-Lora text-4xl text-white m-10">{{link.title}}</h3>
        </div>
    </a>
    {% endfor %}
{% endblock Content %}